language: python

python:
  - 2.7
  - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev

install:
  - pip install -q -r requirements.txt

script:
  - py.test tests
