language: python

python:
  - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev

install:
  - pip install -r requirements.txt

script:
  py.test-2.7 tests
